### ISSUE TITLE
Attunement Altar - Mineralis Not working?

### ISSUE THREAD

**Issue by Teslachu** [TheLimePixel/Crimson-Skies#12]
I do not know if this is by design or if this is a bug, but since the quest book mentions it and I've used astral sorcery before, I have to assume that it is a bug or by design. I know the attunement altar works - It worked with Aevitas and Discidia. However, on the night of finding of Mineralis, I set it up - Saw the constellation reflect on the attunement altar, saw the little squares around the attunement altar table go to the floating position... Stepped on top of it and nothing.  I tried the next night, after breaking down the relays and still nothing. Tried Discidia and it worked.... So is this by design or is this a bug?

**Comment by TheLimePixel** [comment]
Did you remove your previous attunements before that?

**Comment by Teslachu** [comment]
Yes. I removed all previous attunements.
