### ISSUE TITLE
Version 1.1.2 - Can't make sapphires

### ISSUE THREAD

**Issue by TransWorlder** [TheLimePixel/Crimson-Skies#13]
So had this show up in the last version but just updated to 1.1.2 today to confirm. The recipes for making a sapphire at the jewelers table only cover making them from a block of it fragments. I have the ore created, but the only thing I can grind it with would be the astral sorcery grindstone which gives me sapphire dust. The dust however can't be smelted in the forge so have no way to make them.

Had to just delete my ore and spawn 1 gem in to complete the quest as that was locking any further progression in the evil/dark gems.

**Comment by TheLimePixel** [comment]
just break the ore.... *shakes head*
