### ISSUE TITLE
JEI incorrectly shows recipe for Obsidian Pickaxe Head

### ISSUE THREAD

**Issue by mahldcat** [TheLimePixel/Crimson-Skies#23]
he quest "Rock Crystals" needs an obsidian pickaxe head as one of the crafted items.  

When you examine the recipes to craft this pickaxe head in JEI, it shows up as requiring a smeltery (which it not craftable yet), versus having to use the part builder.  

If possible this should be switched out to display the correct recipe.

**Comment by TheLimePixel** [comment]
The Part Builder doesn't have JEI support.
