### ISSUE TITLE
Lenses having no effect

### ISSUE THREAD

**Issue by gentlecrabfish** [TheLimePixel/Crimson-Skies#28]
So i was trying to make an automatic cobble generator with a breaking lens and it did absolutly nothing when it had starlight directly pointed at it, I also tested Burning and damaging And they do nothing.

After later study all of the starlight infusion via lenses and crystals don't seem to work

**Comment by supercrasher** [comment]
I had this happen too and it seems that after playing for a while astral sorcery stuff breaks for some reason and require a MODPACK restart in order to function again

**Comment by TheLimePixel** [comment]
Yup, that happens.
