### ISSUE TITLE
Server Crashing when upgrading from 1.2.2 to 1.2.3

### ISSUE THREAD

**Issue by recanem** [TheLimePixel/Crimson-Skies#31]
[crash-2018-04-16_07.19.31-server.txt](https://github.com/EmosewaPixel/Crimson-Skies/files/1915010/crash-2018-04-16_07.19.31-server.txt)

Tried upgrading world to latest version and getting constant crash - crash log attached...looks like the version of forge needs an update

**Comment by ErosM** [comment]
Hi, 
I have the same problem. I play in a Singleplayer world witch I just updated to version 1.2.3 from 1.2.2.
After the update, as soon as i log in to my world, the game crashes. I think the crash is related to some special mobs added from a mod. If I play in peaceful the game works just fine.

Here's the link to the crash-log on [pastebin](https://pastebin.com/BrLgPKqe)

**Comment by TheLimePixel** [comment]
Update forge.
