### ISSUE TITLE
Crash on 1.2.3 - Single Player

### ISSUE THREAD

**Issue by movieghost** [TheLimePixel/Crimson-Skies#33]
I keep having a crashing problem on the 1.2.3 version, single player.  Here is the crash report: https://pastebin.com/jMdYKzWR

I took a look and the exception appears to be something with the Tombstone mod, but it might just be irrelevant.  I noticed that it had to do with skeleton entities in the exception message, so I set the world to peaceful, and played without problems.  Within a couple of minutes of turning mobs back on (normal difficulty), the crash occurred again.  The time of play to the time of crash appears to be random, so I am assuming it is a specific mob that is spawning, or what seems more likely since it has to do with skeletons and enchantments, it is a skeleton with a certain type of enchanted bow.

This is all guess work, as I haven't dug into any of the code, but it seems plausible based on the exception message, and what I have experienced.

Thanks for all the hard work, I am having a ton of fun with this pack!

**Comment by Adamantion** [comment]
I think i'm having same issue, version 1.2.3. Just started playing Crimson Skies, made a small room for mobs to spawn, then went to bonemeal grass and collect seed and got first crash.
I hope that's not a pain to fix, so we could fully enjoy this awesome pack!

**Comment by ZZaphodd** [comment]
https://github.com/EmosewaPixel/Crimson-Skies/issues/32

hope you guys help, I changed version of tombstone via twich client and work without problem.

![image](https://user-images.githubusercontent.com/8099421/38981550-a346e90e-43fa-11e8-9406-35ba9b87a018.png)

**Comment by Adamantion** [comment]
Thank you, Sir. Worked for me!

**Comment by movieghost** [comment]
Thanks! Upgrading to the latest released worked great!
