### ISSUE TITLE
Can't make obsidian in V1.2.4

### ISSUE THREAD

**Issue by Sanaradain** [TheLimePixel/Crimson-Skies#37]
In version 1.2.4 the Quest book says you should use lots of stone in the luminous crafting table to get obsidian, however the only item i can get out of that is sky stone, you could get it with botania and blaze lamp, but you couldn't pick it up.

**Comment by mkelican** [comment]
There is a recipe for obsidian using the luminous crafting table.  You need two sky stone and two polished stone

**Comment by Sanaradain** [comment]
oddly after restarting the pack a couple of times it now shows up. thank you for responding.
