### ISSUE TITLE
Miniblock changes have broken iron rod recipe. (maybe more)

### ISSUE THREAD

**Issue by MrNinja93** [TheLimePixel/Crimson-Skies#41]
Miniblocks got an internal refactor to make them compatible with more blocks in the past couple of weeks, as part of that some item id's have changed one of which is the stone corner the iron rod recipe uses so progression past that quest is impossible without cheats.

Also the refined hacksaw is not used anymore so the controlled breaking quest requiring it is now outdated.  

Version 1.2.4.1 of the pack

**Comment by TheLimePixel** [comment]
Oh, I fixed the mouldings, but forgot the corners.
