### ISSUE TITLE
Collector crystal no longer changing blocks.

### ISSUE THREAD

**Issue by someguy123456789** [TheLimePixel/Crimson-Skies#45]
I have been sitting here for 4-5 minutes, waiting for it to turn this terracotta into iron ore and nothing has happened. I took out one of the terracotta and replaced it with sand and it wont change either. I've picked up and replaced the crystals and blocks but nothing is happening. I've tried using lens to redirect the light, but it still doesn't work. I've tried focusing the moonlight on the altar, but that does not work anymore. I believe it is something with the collector crystal that is causing the problem.
Edit: Its singleplayer

**Comment by TheLimePixel** [comment]
Relog.
