### ISSUE TITLE
Collector crystal no longer changing blocks.

### ISSUE THREAD

**Issue by someguy123456789** [TheLimePixel/Crimson-Skies#46]
#45 

I tried re-loging, and it still does not work. I have reset my computer and it still does not work.

**Comment by ZZaphodd** [comment]
Can you see the steaming like effect on blocks? If not, check the recipe or weird astral sorcery problem.

How many blocks linked to collector crystals?

It takes longer time if there are more blocks linked.
Break collector crystal and place again and link a single block.

And check the sky, also it takes longer if it’s raining or daytime.

**Comment by someguy123456789** [comment]
A. i can see the steam effect stuff.
B. i had 3 blocks connected to 2 crystals. not sure if the second one helps or not...
And i waited 1 in game day and night and none of the blocks changed...

**Comment by majijn** [comment]
crystals close to eachother steal eachother's starlight, make sure they're not within starlight cannibalizing range

**Comment by someguy123456789** [comment]
I believe i had the crystals in a spot that took too much starlight (I.E. the crafting table and/or the relay.)
