### ISSUE TITLE
[request] alternative/midgame recipe for pistons

### ISSUE THREAD

**Issue by ImelchorI** [TheLimePixel/Crimson-Skies#49]
i was wondering if it would be possible to get another way to make pistons, that isnt bound to mechanical power, and reliance on a kiln, and crafting soul urns.

pistons are a kind of block, that has to be crafted a lot through the course of a game, and it would be nice if the task wasnt quite as painfully manual from a certain point onward, and you have to hand craft these items until the end of the pack.

would be nice if there was a second recipe that replaces the soul urn with a steel gear, so its available about at the time you start up your rf production, metal press and your smeltery.

**Comment by TheLimePixel** [comment]
You don't need a lot of pistons, so no, I'm not going to do that. Sorry.
