### ISSUE TITLE
Can't Make Quartz Seeds Using Grindstone

### ISSUE THREAD

**Issue by MaxAstro** [TheLimePixel/Crimson-Skies#55]
I just got the quest to make nether quartz seeds.  However, the infusion recipe gives me the overworld version of quartz ore, and the grindstone will only grind the nether version of quartz ore.  As a result, I can't make crushed quartz and therefore can't make nether quartz seeds (at least until I have a crusher, which I assume is a fair bit farther down the tech tree).

**Comment by DH00245** [comment]
you can smelt/kiln the quartz ore to get nether quartz, then use the grindstone on it to get the dust for the seed ( a crusher is waaaaaaaay down the line)

**Comment by MaxAstro** [comment]
Further problem: Smelting the ore gives quartz shards, not quartz.  The shards seem to be useless.

**Comment by MaxAstro** [comment]
Further further problem: You CAN'T grindstone nether quartz into dust.

**Comment by DH00245** [comment]
Woops, totally forgot like an idiot, but placing quartz ore and breaking it should give u nether quartz like in vanilla mechanics.

Also, i think i wasn't too clear myself. I was using the quartz grindstone from applied energistics 2, and not the astral sorcery one to get the dust. Hope this helps!

**Comment by MaxAstro** [comment]
Oh wow I didn't even think of just placing and breaking it, I feel like an idiot.  XD
