### ISSUE TITLE
Can't craft the Starlight Infuser

### ISSUE THREAD

**Issue by derethil** [TheLimePixel/Crimson-Skies#57]
I can't seem to craft the Starlight Infuser at all. I've done hours of Googling and from what I understand it should be allowing me to craft it, but it isn't. The recipe is correct and the starlight bar is full, so I have no idea why I can't craft it.  

![image](https://user-images.githubusercontent.com/25184096/40628346-b3864206-6281-11e8-80e6-343b77de3b1a.png)

**Comment by MaxAstro** [comment]
I had a similar problem; I kept removing one item from the recipe, closing the crafting interface, opening it, placing the item back, etc., and after doing that three or four times it finally worked.  I think I also tried breaking the collector crystal and re-placing/linking it.

**Comment by TheLimePixel** [comment]
It's a randomly-occuring issue, hopefully it's fixed in the next version.
