### ISSUE TITLE
Charcoal

### ISSUE THREAD

**Issue by kristu** [TheLimePixel/Crimson-Skies#59]
Cant get charcoal early game for starting botania endoflames, wood pile option is not viable because i need iron nugget for flint and steel... and if i try cheat flint and steel the wood pile vanish after burn :(

**Comment by Monstrel** [comment]
What is the intended progression here?

**Comment by Monstrel** [comment]
Nevermind, the endoflames can use wood (planks, etc). I had problems due to not binding the mana spreader to the mana pool, which made them appear to not accept planks as fuel.
