### ISSUE TITLE
Not an issue, actually a question

### ISSUE THREAD

**Issue by Ctfurlani** [TheLimePixel/Crimson-Skies#69]
I'm trying to make some cakes, to make the rune of winter. But I can't get eggs. Does anyone know an alternative?

**Comment by MrScopi** [comment]
Place pumpkins under starlight and wait

**Comment by Ctfurlani** [comment]
But how do I use the cake in the altar? I gave up and changed my computer time to breed those leporine bees to get the eggs.

**Comment by MrScopi** [comment]
Can you use a pick to grab it? I forgot it spawns placed.

**Comment by Ctfurlani** [comment]
Nope. And silk touch doesn't work either

**Comment by MrScopi** [comment]
Then in that case I'm sorry I can't help. Didn't even know chickens don't
drop eggs.

**Comment by Ctfurlani** [comment]
No problem. I got eggs now. Thanks

**Comment by K1521** [comment]
you can also get some cake through scrap boxes
