### ISSUE TITLE
Version 1.0.0.1 - Rock Crystals

### ISSUE THREAD

**Issue by RyanWakeford** [TheLimePixel/Crimson-Skies#9]
I have 20 rock crystals in my inventory but I cant hand in the quest.

![crimson skies 2](https://user-images.githubusercontent.com/25365115/37171949-5fd1c23e-2307-11e8-843a-6625412987f8.png)
![crimson skies 3](https://user-images.githubusercontent.com/25365115/37171950-5fe6b5fe-2307-11e8-9d9e-59d04f5dad0e.png)
![crimson skies](https://user-images.githubusercontent.com/25365115/37171951-5ff96370-2307-11e8-8f76-41449f8e5e6d.png)

**Comment by RyanWakeford** [comment]
Upgraded to 1.0.0.2 and still unable to hand in

**Comment by thaimichael** [comment]
When you updated did you update the better quest database? bq-admin default load?

**Comment by RyanWakeford** [comment]
ah no haven't, how do I do that?

**Comment by RyanWakeford** [comment]
Ah figured out the command, thanks. I can now progress 👍
